/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[13];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define p1 parms[0] 
 #define pEpoR parms[1] 
 #define lambda1 parms[2] 
 #define lambda2 parms[3] 
 #define p5 parms[4] 
 #define p2 parms[5] 
 #define p3 parms[6] 
 #define p4 parms[7] 
 #define y0_0 parms[8] 
 #define y1_0 parms[9] 
 #define y2_0 parms[10] 
 #define y3_0 parms[11] 
 #define y4_0 parms[12] 
#define tmin range[0]
#define tmax range[1]


void jakstat_initmod(void (* odeparms)(int *, double *)) {
	 int N=13;
	 odeparms(&N, parms);
}

void jakstat_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void jakstat_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1.0*(p1*pEpoR*pow(((1.0-exp(-time*lambda1))*exp(-time*lambda2)),3.0)*y[0])+1.0*(p5*y[4]);
 	 ydot[1] = 1.0*(p1*pEpoR*pow(((1.0-exp(-time*lambda1))*exp(-time*lambda2)),3.0)*y[0])-2.0*(p2*pow(y[1],2.0));
 	 ydot[2] = 1.0*(p2*pow(y[1],2.0))-1.0*(p3*y[2]);
 	 ydot[3] = 1.0*(p3*y[2])-1.0*(p4*y[3]);
 	 ydot[4] = 2.0*(p4*y[3])-1.0*(p5*y[4]);

}

